[package]
name = "mi-sensor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
btleplug = "0.11.5"
futures = "0.3.30"
tokio = { version = "1.38.0", features = ["full"] }
uuid = "1.8.0"
